apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: medisupply
data:
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  USER_SERVICE_URL: "http://user-service.medisupply.svc.cluster.local:8000"
  REDIS_URL: "redis://redis-service.medisupply.svc.cluster.local:6379/0"
  REDIS_ENABLED: "true"
  CACHE_TTL: "300"
  AUTH_DISABLED: "false"

