apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: medisupply
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo-regional
  resources:
    requests:
      storage: 1Gi
