apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: medisupply
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Usar StorageClass por defecto del cluster (no especificar permite usar el default)
  resources:
    requests:
      storage: 1Gi
