apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: medisupply
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Usar StorageClass por defecto de GKE (m√°s compatible)
  resources:
    requests:
      storage: 1Gi
