apiVersion: v1
kind: ConfigMap
metadata:
  name: supplier-service-config
  namespace: medisupply
data:
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  USER_SERVICE_URL: "http://user-service.medisupply.svc.cluster.local:8000"
